version: '3'
services:
  clients-api:
    build: .
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clients
      SPRING_DATASOURCE_USERNAME: builders
      SPRING_DATASOURCE_PASSWORD: platformbuilders
  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: builders
      POSTGRES_PASSWORD: platformbuilders
      POSTGRES_DB: clients